spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/skillful?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    password: root
  jpa:
    show-sql: true
    hibernate:
      globally_quoted_identifiers: true
      ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect

  main:
    allow-bean-definition-overriding: true

jwt:
  secret:
    key: 7Iqk7YyM66W07YOA7L2U65Sp7YG065+9U3ByaW5n6rCV7J2Y7Yqc7YSw7LWc7JuQ67mI7J6F64uI64ukLg==
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true