spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/skillful?useSSL=false&&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${SPRING_DATASOURCE_NAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect


  main:
    allow-bean-definition-overriding: true

jwt:
  secret:
    key: ${JWT_SECRET_KEY}
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
weather:
  api:
    url: https://f-api.github.io/f-api/weather.json
logging:
  level:
    root: info